# Generated by Django 5.1 on 2024-08-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('x_class', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=20)),
            ],
        ),
    ]
